### ISSUE TITLE
ENOSPC: no space left

### ISSUE THREAD

**Issue by c0z0** [torbensky/go-now-builder#2]
Hey, you did some awesome work on this project, and I found it very useful. But I ran into a problem. While trying to deploy a project I hit the disk space limit (which I think is set at 500mb) when I added a 5th lambda. I got it working for now by merging two lambdas together, thus having only 4 functions. Taking into account that this hacky fix worked, I believe that the builder is mostly at fault. (maybe it generates unnecessary copies of things that could be shared across lambdas like go binaries or maybe the vendor directory? ). I'm willing to help with a PR if you think such improvements can be made, as I am not 100% sure how this builder works.

With further improvements, I also think we could add features of this project to the official zeit builder which is currently very limited.

Here is the repository I am talking about:

https://github.com/c0z0/lambda-shrt

It also includes a frontend build with nextjs, but I am certain that it doesn't cause any issues because I tried deploying the frontend and api separately and only the api fails regardless if it is built together with the next app.

**Comment by c0z0** [comment]
This is how the error looks like
```
running go build...
2019-01-15T21:40:25.449Z  # command-line-arguments
                          /tmp/75afb1df/pkg/tool/linux_amd64/link: flushing $WORK/b001/exe/a.out: write $WORK/b001/exe/a.out: no space left on device
2019-01-15T21:40:25.451Z  failed to `go build`
2019-01-15T21:40:25.453Z  { Error: Command failed: /tmp/75afb1df/bin/go build -mod=vendor -o /tmp/2bb9a0cb/api/cmd/upload/handler /tmp/22b25546/src/lambda/api/cmd/upload/main__now__go__.go /tmp/22b25546/src/lambda/api/cmd/upload/lambda.go
                              at makeError (/tmp/utils/build-module/node_modules/execa/index.js:174:9)
                              at Promise.all.then.arr (/tmp/utils/build-module/node_modules/execa/index.js:278:16)
                              at <anonymous>
                              at process._tickCallback (internal/process/next_tick.js:188:7)
                            code: 2,
                            stdout: null,
                            stderr: null,
                            failed: true,
                            signal: null,
                            cmd: '/tmp/75afb1df/bin/go build -mod=vendor -o /tmp/2bb9a0cb/api/cmd/upload/handler /tmp/22b25546/src/lambda/api/cmd/upload/main__now__go__.go /tmp/22b25546/src/lambda/api/cmd/upload/lambda.go',
                            timedOut: false,
                            killed: false }
2019-01-15T21:40:25.453Z  patching https://api-bru1.zeit.co/v2/now/deployments/dpl_2hoi2iL6eoUBUHQERv6yzFazjnL5/builds/bld_m2qgdeob1 with {"readyState":"ERROR","errorCode":"BUILD_FAILED_2"}
```
